// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXU-vg4oC1smFCt4RTaZOcQ9tbnBvFqA',
    appId: '1:571501237987:web:9cb406d3eac4b4c2dc17d6',
    messagingSenderId: '571501237987',
    projectId: 'ride-lanka-bc197',
    authDomain: 'ride-lanka-bc197.firebaseapp.com',
    storageBucket: 'ride-lanka-bc197.firebasestorage.app',
    measurementId: 'G-1D1HM0BP17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf0l1ooJhuvjnYdMYUcJ8D1IgeDlNZrKA',
    appId: '1:571501237987:android:a5b639df339c44aadc17d6',
    messagingSenderId: '571501237987',
    projectId: 'ride-lanka-bc197',
    storageBucket: 'ride-lanka-bc197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHIXIZPT4GZxCBtCun9bkIpZanSNYQGKU',
    appId: '1:571501237987:ios:54e417139594a80fdc17d6',
    messagingSenderId: '571501237987',
    projectId: 'ride-lanka-bc197',
    storageBucket: 'ride-lanka-bc197.firebasestorage.app',
    iosBundleId: 'com.example.rideLanka',
  );
}
