// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEL61TRoUex1li4UaJir4R1UvdEwsKuSg',
    appId: '1:663316761309:web:32698555a3ca3f5eaa2934',
    messagingSenderId: '663316761309',
    projectId: 'ride-lanka-d4d5e',
    authDomain: 'ride-lanka-d4d5e.firebaseapp.com',
    storageBucket: 'ride-lanka-d4d5e.firebasestorage.app',
    measurementId: 'G-Y4FCV3Y6KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4BfEwMQtbRlaCR-9NRKYAABXn054X08Q',
    appId: '1:663316761309:android:8e63613d1919be98aa2934',
    messagingSenderId: '663316761309',
    projectId: 'ride-lanka-d4d5e',
    storageBucket: 'ride-lanka-d4d5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRaBlutd6P9RwSWbEYMvJvqaIW4mns9I',
    appId: '1:663316761309:ios:fe27190326a80a77aa2934',
    messagingSenderId: '663316761309',
    projectId: 'ride-lanka-d4d5e',
    storageBucket: 'ride-lanka-d4d5e.firebasestorage.app',
    iosBundleId: 'com.example.rideLanka',
  );

}