// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpxn-zJbe34f7cX03HZledGJ6ONjZ_zUI',
    appId: '1:5795734215:web:849432af79852b435014e2',
    messagingSenderId: '5795734215',
    projectId: 'ride-lanka',
    authDomain: 'ride-lanka.firebaseapp.com',
    storageBucket: 'ride-lanka.firebasestorage.app',
    measurementId: 'G-0ZELRXZJFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjQE0mrB2kOzAuuWWTJ4xXTX9tabbXl0',
    appId: '1:5795734215:android:69a0694d215feaa15014e2',
    messagingSenderId: '5795734215',
    projectId: 'ride-lanka',
    storageBucket: 'ride-lanka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnMqllTMfMAQiGERqZ6KjhF25U9JEi0N8',
    appId: '1:5795734215:ios:09d2ff9c570a21605014e2',
    messagingSenderId: '5795734215',
    projectId: 'ride-lanka',
    storageBucket: 'ride-lanka.firebasestorage.app',
    iosBundleId: 'com.example.rideLanka',
  );
}
